// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'job_info.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_JobInfo _$JobInfoFromJson(Map<String, dynamic> json) => _JobInfo(
  id: json['id'] as String,
  subId: json['subId'] as String?,
  title: json['title'] as String,
  description: json['description'] as String,
  url: json['url'] as String,
  relativeDate: json['relativeDate'] as String?,
  absoluteDate: json['absoluteDate'] as String?,
  budget: (json['budget'] as num?)?.toDouble(),
  jobType: $enumDecode(_$JobTypeEnumMap, json['jobType']),
  experienceLevel: $enumDecode(
    _$ExperienceLevelEnumMap,
    json['experienceLevel'],
  ),
  clientLocation: json['clientLocation'] == null
      ? null
      : ClientLocation.fromJson(json['clientLocation'] as Map<String, dynamic>),
  paymentVerifiedStatus: $enumDecode(
    _$PaymentVerifiedStatusEnumMap,
    json['paymentVerifiedStatus'],
  ),
  allowedApplicantCountries:
      (json['allowedApplicantCountries'] as List<dynamic>)
          .map((e) => ClientLocation.fromJson(e as Map<String, dynamic>))
          .toList(),
  clientName: json['clientName'] as String?,
  clientNameConfidencePercent: (json['clientNameConfidencePercent'] as num?)
      ?.toDouble(),
  clientAvgHourlyRate: (json['clientAvgHourlyRate'] as num?)?.toDouble(),
  clientRating: (json['clientRating'] as num?)?.toDouble(),
  clientHireRatePercent: (json['clientHireRatePercent'] as num?)?.toDouble(),
  clientTotalSpent: (json['clientTotalSpent'] as num?)?.toDouble(),
  tags: (json['tags'] as List<dynamic>).map((e) => e as String).toList(),
  hasHired: json['hasHired'] as bool,
  questions: (json['questions'] as List<dynamic>)
      .map((e) => Question.fromJson(e as Map<String, dynamic>))
      .toList(),
);

Map<String, dynamic> _$JobInfoToJson(_JobInfo instance) => <String, dynamic>{
  'id': instance.id,
  'subId': instance.subId,
  'title': instance.title,
  'description': instance.description,
  'url': instance.url,
  'relativeDate': instance.relativeDate,
  'absoluteDate': instance.absoluteDate,
  'budget': instance.budget,
  'jobType': _$JobTypeEnumMap[instance.jobType]!,
  'experienceLevel': _$ExperienceLevelEnumMap[instance.experienceLevel]!,
  'clientLocation': instance.clientLocation,
  'paymentVerifiedStatus':
      _$PaymentVerifiedStatusEnumMap[instance.paymentVerifiedStatus]!,
  'allowedApplicantCountries': instance.allowedApplicantCountries,
  'clientName': instance.clientName,
  'clientNameConfidencePercent': instance.clientNameConfidencePercent,
  'clientAvgHourlyRate': instance.clientAvgHourlyRate,
  'clientRating': instance.clientRating,
  'clientHireRatePercent': instance.clientHireRatePercent,
  'clientTotalSpent': instance.clientTotalSpent,
  'tags': instance.tags,
  'hasHired': instance.hasHired,
  'questions': instance.questions,
};

const _$JobTypeEnumMap = {JobType.fixed: 'fixed', JobType.hourly: 'hourly'};

const _$ExperienceLevelEnumMap = {
  ExperienceLevel.entryLevel: 'entryLevel',
  ExperienceLevel.intermediate: 'intermediate',
  ExperienceLevel.expert: 'expert',
};

const _$PaymentVerifiedStatusEnumMap = {
  PaymentVerifiedStatus.unknown: 'unknown',
  PaymentVerifiedStatus.verified: 'verified',
  PaymentVerifiedStatus.unverified: 'unverified',
};

_ClientLocationCountry _$ClientLocationCountryFromJson(
  Map<String, dynamic> json,
) => _ClientLocationCountry(
  country: $enumDecode(_$CountryEnumMap, json['country']),
  $type: json['runtimeType'] as String?,
);

Map<String, dynamic> _$ClientLocationCountryToJson(
  _ClientLocationCountry instance,
) => <String, dynamic>{
  'country': _$CountryEnumMap[instance.country]!,
  'runtimeType': instance.$type,
};

const _$CountryEnumMap = {
  Country.albania: 'albania',
  Country.algeria: 'algeria',
  Country.americanSamoa: 'americanSamoa',
  Country.andorra: 'andorra',
  Country.angola: 'angola',
  Country.anguilla: 'anguilla',
  Country.antiguaAndBarbuda: 'antiguaAndBarbuda',
  Country.argentina: 'argentina',
  Country.armenia: 'armenia',
  Country.aruba: 'aruba',
  Country.australia: 'australia',
  Country.austria: 'austria',
  Country.azerbaijan: 'azerbaijan',
  Country.bahamas: 'bahamas',
  Country.bahrain: 'bahrain',
  Country.bangladesh: 'bangladesh',
  Country.barbados: 'barbados',
  Country.belgium: 'belgium',
  Country.belize: 'belize',
  Country.benin: 'benin',
  Country.bermuda: 'bermuda',
  Country.bhutan: 'bhutan',
  Country.bolivia: 'bolivia',
  Country.bonaireSintEustatiusAndSaba: 'bonaireSintEustatiusAndSaba',
  Country.bosniaAndHerzegovina: 'bosniaAndHerzegovina',
  Country.botswana: 'botswana',
  Country.bouvetIsland: 'bouvetIsland',
  Country.brazil: 'brazil',
  Country.britishIndianOceanTerritory: 'britishIndianOceanTerritory',
  Country.britishVirginIslands: 'britishVirginIslands',
  Country.bruneiDarussalam: 'bruneiDarussalam',
  Country.bulgaria: 'bulgaria',
  Country.burkinaFaso: 'burkinaFaso',
  Country.burundi: 'burundi',
  Country.cambodia: 'cambodia',
  Country.cameroon: 'cameroon',
  Country.canada: 'canada',
  Country.capeVerde: 'capeVerde',
  Country.caymanIslands: 'caymanIslands',
  Country.centralAfricanRepublic: 'centralAfricanRepublic',
  Country.chad: 'chad',
  Country.chile: 'chile',
  Country.china: 'china',
  Country.christmasIsland: 'christmasIsland',
  Country.cocosKeelingIslands: 'cocosKeelingIslands',
  Country.colombia: 'colombia',
  Country.comoros: 'comoros',
  Country.congo: 'congo',
  Country.congoDemocraticRepublicOfThe: 'congoDemocraticRepublicOfThe',
  Country.cookIslands: 'cookIslands',
  Country.costaRica: 'costaRica',
  Country.coteDIvoire: 'coteDIvoire',
  Country.croatia: 'croatia',
  Country.curacao: 'curacao',
  Country.cyprus: 'cyprus',
  Country.czechRepublic: 'czechRepublic',
  Country.denmark: 'denmark',
  Country.djibouti: 'djibouti',
  Country.dominica: 'dominica',
  Country.dominicanRepublic: 'dominicanRepublic',
  Country.ecuador: 'ecuador',
  Country.egypt: 'egypt',
  Country.elSalvador: 'elSalvador',
  Country.equatorialGuinea: 'equatorialGuinea',
  Country.eritrea: 'eritrea',
  Country.estonia: 'estonia',
  Country.ethiopia: 'ethiopia',
  Country.falklandIslands: 'falklandIslands',
  Country.faroeIslands: 'faroeIslands',
  Country.fiji: 'fiji',
  Country.finland: 'finland',
  Country.france: 'france',
  Country.frenchGuiana: 'frenchGuiana',
  Country.frenchPolynesia: 'frenchPolynesia',
  Country.frenchSouthernAndAntarcticLands: 'frenchSouthernAndAntarcticLands',
  Country.gabon: 'gabon',
  Country.gambia: 'gambia',
  Country.georgia: 'georgia',
  Country.germany: 'germany',
  Country.ghana: 'ghana',
  Country.gibraltar: 'gibraltar',
  Country.greece: 'greece',
  Country.greenland: 'greenland',
  Country.grenada: 'grenada',
  Country.guadeloupe: 'guadeloupe',
  Country.guam: 'guam',
  Country.guatemala: 'guatemala',
  Country.guernsey: 'guernsey',
  Country.guinea: 'guinea',
  Country.guineaBissau: 'guineaBissau',
  Country.guyana: 'guyana',
  Country.haiti: 'haiti',
  Country.heardIslandAndMcDonaldIslands: 'heardIslandAndMcDonaldIslands',
  Country.holySee: 'holySee',
  Country.honduras: 'honduras',
  Country.hongKong: 'hongKong',
  Country.hungary: 'hungary',
  Country.iceland: 'iceland',
  Country.india: 'india',
  Country.indonesia: 'indonesia',
  Country.ireland: 'ireland',
  Country.isleOfMan: 'isleOfMan',
  Country.israel: 'israel',
  Country.italy: 'italy',
  Country.jamaica: 'jamaica',
  Country.japan: 'japan',
  Country.jersey: 'jersey',
  Country.jordan: 'jordan',
  Country.kazakhstan: 'kazakhstan',
  Country.kenya: 'kenya',
  Country.kiribati: 'kiribati',
  Country.kuwait: 'kuwait',
  Country.kyrgyzstan: 'kyrgyzstan',
  Country.laos: 'laos',
  Country.latvia: 'latvia',
  Country.lebanon: 'lebanon',
  Country.lesotho: 'lesotho',
  Country.liechtenstein: 'liechtenstein',
  Country.lithuania: 'lithuania',
  Country.luxembourg: 'luxembourg',
  Country.macao: 'macao',
  Country.macedonia: 'macedonia',
  Country.madagascar: 'madagascar',
  Country.malawi: 'malawi',
  Country.malaysia: 'malaysia',
  Country.maldives: 'maldives',
  Country.mali: 'mali',
  Country.malta: 'malta',
  Country.marshallIslands: 'marshallIslands',
  Country.martinique: 'martinique',
  Country.mauritania: 'mauritania',
  Country.mauritius: 'mauritius',
  Country.mayotte: 'mayotte',
  Country.mexico: 'mexico',
  Country.micronesiaFederatedStatesOf: 'micronesiaFederatedStatesOf',
  Country.moldova: 'moldova',
  Country.monaco: 'monaco',
  Country.mongolia: 'mongolia',
  Country.montenegro: 'montenegro',
  Country.montserrat: 'montserrat',
  Country.morocco: 'morocco',
  Country.mozambique: 'mozambique',
  Country.myanmar: 'myanmar',
  Country.namibia: 'namibia',
  Country.nauru: 'nauru',
  Country.nepal: 'nepal',
  Country.netherlands: 'netherlands',
  Country.netherlandsAntilles: 'netherlandsAntilles',
  Country.newCaledonia: 'newCaledonia',
  Country.newZealand: 'newZealand',
  Country.nicaragua: 'nicaragua',
  Country.niger: 'niger',
  Country.nigeria: 'nigeria',
  Country.niue: 'niue',
  Country.norfolkIsland: 'norfolkIsland',
  Country.northernMarianaIslands: 'northernMarianaIslands',
  Country.norway: 'norway',
  Country.oman: 'oman',
  Country.pakistan: 'pakistan',
  Country.palau: 'palau',
  Country.palestinianTerritories: 'palestinianTerritories',
  Country.panama: 'panama',
  Country.papuaNewGuinea: 'papuaNewGuinea',
  Country.paraguay: 'paraguay',
  Country.peru: 'peru',
  Country.philippines: 'philippines',
  Country.pitcairn: 'pitcairn',
  Country.poland: 'poland',
  Country.portugal: 'portugal',
  Country.puertoRico: 'puertoRico',
  Country.qatar: 'qatar',
  Country.reunion: 'reunion',
  Country.romania: 'romania',
  Country.rwanda: 'rwanda',
  Country.saintBarthelemy: 'saintBarthelemy',
  Country.saintHelena: 'saintHelena',
  Country.saintKittsAndNevis: 'saintKittsAndNevis',
  Country.saintLucia: 'saintLucia',
  Country.saintMartinFrenchPart: 'saintMartinFrenchPart',
  Country.saintPierreAndMiquelon: 'saintPierreAndMiquelon',
  Country.saintVincentAndTheGrenadines: 'saintVincentAndTheGrenadines',
  Country.samoa: 'samoa',
  Country.sanMarino: 'sanMarino',
  Country.saoTomeAndPrincipe: 'saoTomeAndPrincipe',
  Country.saudiArabia: 'saudiArabia',
  Country.senegal: 'senegal',
  Country.serbia: 'serbia',
  Country.seychelles: 'seychelles',
  Country.sierraLeone: 'sierraLeone',
  Country.singapore: 'singapore',
  Country.sintMaartenDutchPart: 'sintMaartenDutchPart',
  Country.slovakia: 'slovakia',
  Country.slovenia: 'slovenia',
  Country.solomonIslands: 'solomonIslands',
  Country.somalia: 'somalia',
  Country.southAfrica: 'southAfrica',
  Country.southKorea: 'southKorea',
  Country.spain: 'spain',
  Country.sriLanka: 'sriLanka',
  Country.suriname: 'suriname',
  Country.svalbardAndJanMayen: 'svalbardAndJanMayen',
  Country.swaziland: 'swaziland',
  Country.sweden: 'sweden',
  Country.switzerland: 'switzerland',
  Country.taiwan: 'taiwan',
  Country.tajikistan: 'tajikistan',
  Country.tanzania: 'tanzania',
  Country.thailand: 'thailand',
  Country.timorLeste: 'timorLeste',
  Country.togo: 'togo',
  Country.tokelau: 'tokelau',
  Country.tonga: 'tonga',
  Country.trinidadAndTobago: 'trinidadAndTobago',
  Country.tunisia: 'tunisia',
  Country.turkey: 'turkey',
  Country.turkmenistan: 'turkmenistan',
  Country.turksAndCaicosIslands: 'turksAndCaicosIslands',
  Country.tuvalu: 'tuvalu',
  Country.uganda: 'uganda',
  Country.ukraine: 'ukraine',
  Country.unitedArabEmirates: 'unitedArabEmirates',
  Country.unitedKingdom: 'unitedKingdom',
  Country.unitedStates: 'unitedStates',
  Country.unitedStatesMinorOutlyingIslands: 'unitedStatesMinorOutlyingIslands',
  Country.unitedStatesVirginIslands: 'unitedStatesVirginIslands',
  Country.uruguay: 'uruguay',
  Country.uzbekistan: 'uzbekistan',
  Country.vanuatu: 'vanuatu',
  Country.venezuela: 'venezuela',
  Country.vietnam: 'vietnam',
  Country.wallisAndFutuna: 'wallisAndFutuna',
  Country.westernSahara: 'westernSahara',
  Country.yemen: 'yemen',
  Country.zambia: 'zambia',
  Country.zimbabwe: 'zimbabwe',
};

_ClientLocationRegion _$ClientLocationRegionFromJson(
  Map<String, dynamic> json,
) => _ClientLocationRegion(
  region: $enumDecode(_$RegionEnumMap, json['region']),
  $type: json['runtimeType'] as String?,
);

Map<String, dynamic> _$ClientLocationRegionToJson(
  _ClientLocationRegion instance,
) => <String, dynamic>{
  'region': _$RegionEnumMap[instance.region]!,
  'runtimeType': instance.$type,
};

const _$RegionEnumMap = {
  Region.africa: 'africa',
  Region.americas: 'americas',
  Region.antarctica: 'antarctica',
  Region.asia: 'asia',
  Region.europe: 'europe',
  Region.oceania: 'oceania',
};

_ClientLocationSubRegion _$ClientLocationSubRegionFromJson(
  Map<String, dynamic> json,
) => _ClientLocationSubRegion(
  subRegion: $enumDecode(_$SubRegionEnumMap, json['subRegion']),
  $type: json['runtimeType'] as String?,
);

Map<String, dynamic> _$ClientLocationSubRegionToJson(
  _ClientLocationSubRegion instance,
) => <String, dynamic>{
  'subRegion': _$SubRegionEnumMap[instance.subRegion]!,
  'runtimeType': instance.$type,
};

const _$SubRegionEnumMap = {
  SubRegion.australiaAndNewZealand: 'australiaAndNewZealand',
  SubRegion.caribbean: 'caribbean',
  SubRegion.centralAmerica: 'centralAmerica',
  SubRegion.centralAsia: 'centralAsia',
  SubRegion.easternAfrica: 'easternAfrica',
  SubRegion.easternAsia: 'easternAsia',
  SubRegion.easternEurope: 'easternEurope',
  SubRegion.melanesia: 'melanesia',
  SubRegion.micronesia: 'micronesia',
  SubRegion.middleAfrica: 'middleAfrica',
  SubRegion.northernAfrica: 'northernAfrica',
  SubRegion.northernAmerica: 'northernAmerica',
  SubRegion.northernEurope: 'northernEurope',
  SubRegion.polynesia: 'polynesia',
  SubRegion.southAmerica: 'southAmerica',
  SubRegion.southEasternAsia: 'southEasternAsia',
  SubRegion.southernAfrica: 'southernAfrica',
  SubRegion.southernAsia: 'southernAsia',
  SubRegion.southernEurope: 'southernEurope',
  SubRegion.westernAfrica: 'westernAfrica',
  SubRegion.westernAsia: 'westernAsia',
  SubRegion.westernEurope: 'westernEurope',
};

_Question _$QuestionFromJson(Map<String, dynamic> json) => _Question(
  question: json['question'] as String,
  positionIndex: (json['positionIndex'] as num).toInt(),
);

Map<String, dynamic> _$QuestionToJson(_Question instance) => <String, dynamic>{
  'question': instance.question,
  'positionIndex': instance.positionIndex,
};
