import '../generated/protocol.dart';

const Map<Region, String> _regionDisplayNames = {
  Region.africa: 'Africa',
  Region.americas: 'Americas',
  Region.antarctica: 'Antarctica',
  Region.asia: 'Asia',
  Region.europe: 'Europe',
  Region.oceania: 'Oceania',
};

const Map<SubRegion, String> _subRegionDisplayNames = {
  SubRegion.australiaAndNewZealand: 'Australia and New Zealand',
  SubRegion.caribbean: 'Caribbean',
  SubRegion.centralAmerica: 'Central America',
  SubRegion.centralAsia: 'Central Asia',
  SubRegion.easternAfrica: 'Eastern Africa',
  SubRegion.easternAsia: 'Eastern Asia',
  SubRegion.easternEurope: 'Eastern Europe',
  SubRegion.melanesia: 'Melanesia',
  SubRegion.micronesia: 'Micronesia',
  SubRegion.middleAfrica: 'Middle Africa',
  SubRegion.northernAfrica: 'Northern Africa',
  SubRegion.northernAmerica: 'Northern America',
  SubRegion.northernEurope: 'Northern Europe',
  SubRegion.polynesia: 'Polynesia',
  SubRegion.southAmerica: 'South America',
  SubRegion.southEasternAsia: 'South-Eastern Asia',
  SubRegion.southernAfrica: 'Southern Africa',
  SubRegion.southernAsia: 'Southern Asia',
  SubRegion.southernEurope: 'Southern Europe',
  SubRegion.westernAfrica: 'Western Africa',
  SubRegion.westernAsia: 'Western Asia',
  SubRegion.westernEurope: 'Western Europe',
};

const Map<Country, String> _countryDisplayNames = {
  Country.albania: 'Albania',
  Country.algeria: 'Algeria',
  Country.americanSamoa: 'American Samoa',
  Country.andorra: 'Andorra',
  Country.angola: 'Angola',
  Country.anguilla: 'Anguilla',
  Country.antiguaAndBarbuda: 'Antigua and Barbuda',
  Country.argentina: 'Argentina',
  Country.armenia: 'Armenia',
  Country.aruba: 'Aruba',
  Country.australia: 'Australia',
  Country.austria: 'Austria',
  Country.azerbaijan: 'Azerbaijan',
  Country.bahamas: 'Bahamas',
  Country.bahrain: 'Bahrain',
  Country.bangladesh: 'Bangladesh',
  Country.barbados: 'Barbados',
  Country.belgium: 'Belgium',
  Country.belize: 'Belize',
  Country.benin: 'Benin',
  Country.bermuda: 'Bermuda',
  Country.bhutan: 'Bhutan',
  Country.bolivia: 'Bolivia',
  Country.bonaireSintEustatiusAndSaba: 'Bonaire, Sint Eustatius and Saba',
  Country.bosniaAndHerzegovina: 'Bosnia and Herzegovina',
  Country.botswana: 'Botswana',
  Country.bouvetIsland: 'Bouvet Island',
  Country.brazil: 'Brazil',
  Country.britishIndianOceanTerritory: 'British Indian Ocean Territory',
  Country.britishVirginIslands: 'British Virgin Islands',
  Country.bruneiDarussalam: 'Brunei Darussalam',
  Country.bulgaria: 'Bulgaria',
  Country.burkinaFaso: 'Burkina Faso',
  Country.burundi: 'Burundi',
  Country.cambodia: 'Cambodia',
  Country.cameroon: 'Cameroon',
  Country.canada: 'Canada',
  Country.capeVerde: 'Cape Verde',
  Country.caymanIslands: 'Cayman Islands',
  Country.centralAfricanRepublic: 'Central African Republic',
  Country.chad: 'Chad',
  Country.chile: 'Chile',
  Country.china: 'China',
  Country.christmasIsland: 'Christmas Island',
  Country.cocosKeelingIslands: 'Cocos (Keeling) Islands',
  Country.colombia: 'Colombia',
  Country.comoros: 'Comoros',
  Country.congo: 'Congo',
  Country.congoDemocraticRepublicOfThe: 'Congo, the Democratic Republic of the',
  Country.cookIslands: 'Cook Islands',
  Country.costaRica: 'Costa Rica',
  Country.coteDIvoire: 'Cote d\'Ivoire',
  Country.croatia: 'Croatia',
  Country.curacao: 'Curacao',
  Country.cyprus: 'Cyprus',
  Country.czechRepublic: 'Czech Republic',
  Country.denmark: 'Denmark',
  Country.djibouti: 'Djibouti',
  Country.dominica: 'Dominica',
  Country.dominicanRepublic: 'Dominican Republic',
  Country.ecuador: 'Ecuador',
  Country.egypt: 'Egypt',
  Country.elSalvador: 'El Salvador',
  Country.equatorialGuinea: 'Equatorial Guinea',
  Country.eritrea: 'Eritrea',
  Country.estonia: 'Estonia',
  Country.ethiopia: 'Ethiopia',
  Country.falklandIslands: 'Falkland Islands',
  Country.faroeIslands: 'Faroe Islands',
  Country.fiji: 'Fiji',
  Country.finland: 'Finland',
  Country.france: 'France',
  Country.frenchGuiana: 'French Guiana',
  Country.frenchPolynesia: 'French Polynesia',
  Country.frenchSouthernAndAntarcticLands:
      'French Southern and Antarctic Lands',
  Country.gabon: 'Gabon',
  Country.gambia: 'Gambia',
  Country.georgia: 'Georgia',
  Country.germany: 'Germany',
  Country.ghana: 'Ghana',
  Country.gibraltar: 'Gibraltar',
  Country.greece: 'Greece',
  Country.greenland: 'Greenland',
  Country.grenada: 'Grenada',
  Country.guadeloupe: 'Guadeloupe',
  Country.guam: 'Guam',
  Country.guatemala: 'Guatemala',
  Country.guernsey: 'Guernsey',
  Country.guinea: 'Guinea',
  Country.guineaBissau: 'Guinea-Bissau',
  Country.guyana: 'Guyana',
  Country.haiti: 'Haiti',
  Country.heardIslandAndMcDonaldIslands: 'Heard Island and McDonald Islands',
  Country.holySee: 'Holy See',
  Country.honduras: 'Honduras',
  Country.hongKong: 'Hong Kong',
  Country.hungary: 'Hungary',
  Country.iceland: 'Iceland',
  Country.india: 'India',
  Country.indonesia: 'Indonesia',
  Country.ireland: 'Ireland',
  Country.isleOfMan: 'Isle of Man',
  Country.israel: 'Israel',
  Country.italy: 'Italy',
  Country.jamaica: 'Jamaica',
  Country.japan: 'Japan',
  Country.jersey: 'Jersey',
  Country.jordan: 'Jordan',
  Country.kazakhstan: 'Kazakhstan',
  Country.kenya: 'Kenya',
  Country.kiribati: 'Kiribati',
  Country.kuwait: 'Kuwait',
  Country.kyrgyzstan: 'Kyrgyzstan',
  Country.laos: 'Laos',
  Country.latvia: 'Latvia',
  Country.lebanon: 'Lebanon',
  Country.lesotho: 'Lesotho',
  Country.liechtenstein: 'Liechtenstein',
  Country.lithuania: 'Lithuania',
  Country.luxembourg: 'Luxembourg',
  Country.macao: 'Macao',
  Country.macedonia: 'Macedonia',
  Country.madagascar: 'Madagascar',
  Country.malawi: 'Malawi',
  Country.malaysia: 'Malaysia',
  Country.maldives: 'Maldives',
  Country.mali: 'Mali',
  Country.malta: 'Malta',
  Country.marshallIslands: 'Marshall Islands',
  Country.martinique: 'Martinique',
  Country.mauritania: 'Mauritania',
  Country.mauritius: 'Mauritius',
  Country.mayotte: 'Mayotte',
  Country.mexico: 'Mexico',
  Country.micronesiaFederatedStatesOf: 'Micronesia, Federated States of',
  Country.moldova: 'Moldova',
  Country.monaco: 'Monaco',
  Country.mongolia: 'Mongolia',
  Country.montenegro: 'Montenegro',
  Country.montserrat: 'Montserrat',
  Country.morocco: 'Morocco',
  Country.mozambique: 'Mozambique',
  Country.myanmar: 'Myanmar',
  Country.namibia: 'Namibia',
  Country.nauru: 'Nauru',
  Country.nepal: 'Nepal',
  Country.netherlands: 'Netherlands',
  Country.netherlandsAntilles: 'Netherlands Antilles',
  Country.newCaledonia: 'New Caledonia',
  Country.newZealand: 'New Zealand',
  Country.nicaragua: 'Nicaragua',
  Country.niger: 'Niger',
  Country.nigeria: 'Nigeria',
  Country.niue: 'Niue',
  Country.norfolkIsland: 'Norfolk Island',
  Country.northernMarianaIslands: 'Northern Mariana Islands',
  Country.norway: 'Norway',
  Country.oman: 'Oman',
  Country.pakistan: 'Pakistan',
  Country.palau: 'Palau',
  Country.palestinianTerritories: 'Palestinian Territories',
  Country.panama: 'Panama',
  Country.papuaNewGuinea: 'Papua New Guinea',
  Country.paraguay: 'Paraguay',
  Country.peru: 'Peru',
  Country.philippines: 'Philippines',
  Country.pitcairn: 'Pitcairn',
  Country.poland: 'Poland',
  Country.portugal: 'Portugal',
  Country.puertoRico: 'Puerto Rico',
  Country.qatar: 'Qatar',
  Country.reunion: 'Reunion',
  Country.romania: 'Romania',
  Country.rwanda: 'Rwanda',
  Country.saintBarthelemy: 'Saint Barthelemy',
  Country.saintHelena: 'Saint Helena',
  Country.saintKittsAndNevis: 'Saint Kitts and Nevis',
  Country.saintLucia: 'Saint Lucia',
  Country.saintMartinFrenchPart: 'Saint Martin (French part)',
  Country.saintPierreAndMiquelon: 'Saint Pierre and Miquelon',
  Country.saintVincentAndTheGrenadines: 'Saint Vincent and the Grenadines',
  Country.samoa: 'Samoa',
  Country.sanMarino: 'San Marino',
  Country.saoTomeAndPrincipe: 'Sao Tome and Principe',
  Country.saudiArabia: 'Saudi Arabia',
  Country.senegal: 'Senegal',
  Country.serbia: 'Serbia',
  Country.seychelles: 'Seychelles',
  Country.sierraLeone: 'Sierra Leone',
  Country.singapore: 'Singapore',
  Country.sintMaartenDutchPart: 'Sint Maarten (Dutch part)',
  Country.slovakia: 'Slovakia',
  Country.slovenia: 'Slovenia',
  Country.solomonIslands: 'Solomon Islands',
  Country.somalia: 'Somalia',
  Country.southAfrica: 'South Africa',
  Country.southKorea: 'South Korea',
  Country.spain: 'Spain',
  Country.sriLanka: 'Sri Lanka',
  Country.suriname: 'Suriname',
  Country.svalbardAndJanMayen: 'Svalbard and Jan Mayen',
  Country.swaziland: 'Swaziland',
  Country.sweden: 'Sweden',
  Country.switzerland: 'Switzerland',
  Country.taiwan: 'Taiwan',
  Country.tajikistan: 'Tajikistan',
  Country.tanzania: 'Tanzania',
  Country.thailand: 'Thailand',
  Country.timorLeste: 'Timor-Leste',
  Country.togo: 'Togo',
  Country.tokelau: 'Tokelau',
  Country.tonga: 'Tonga',
  Country.trinidadAndTobago: 'Trinidad and Tobago',
  Country.tunisia: 'Tunisia',
  Country.turkey: 'Turkey',
  Country.turkmenistan: 'Turkmenistan',
  Country.turksAndCaicosIslands: 'Turks and Caicos Islands',
  Country.tuvalu: 'Tuvalu',
  Country.uganda: 'Uganda',
  Country.ukraine: 'Ukraine',
  Country.unitedArabEmirates: 'United Arab Emirates',
  Country.unitedKingdom: 'United Kingdom',
  Country.unitedStates: 'United States',
  Country.unitedStatesMinorOutlyingIslands:
      'United States Minor Outlying Islands',
  Country.unitedStatesVirginIslands: 'United States Virgin Islands',
  Country.uruguay: 'Uruguay',
  Country.uzbekistan: 'Uzbekistan',
  Country.vanuatu: 'Vanuatu',
  Country.venezuela: 'Venezuela',
  Country.vietnam: 'Vietnam',
  Country.wallisAndFutuna: 'Wallis and Futuna',
  Country.westernSahara: 'Western Sahara',
  Country.yemen: 'Yemen',
  Country.zambia: 'Zambia',
  Country.zimbabwe: 'Zimbabwe',
};

extension RegionUpworkLabelX on Region {
  String get displayName => _regionDisplayNames[this]!;
}

extension SubRegionUpworkLabelX on SubRegion {
  String get displayName => _subRegionDisplayNames[this]!;
}

extension CountryUpworkLabelX on Country {
  String get displayName => _countryDisplayNames[this]!;
}
