name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      VERSION: '3.4.2'
      SERVERPOD_PASSWORD_database: 's1DF2J9tn5T_DalPZWwgTg-3zNZ4Es8e'
      SERVERPOD_PASSWORD_redis: 'mPFk_3JrIk00k3VivA2MLH5zPy0hVBTf'

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.8'

      - name: Start containers
        working-directory: pascoa_scout_server
        run: docker compose up --quiet-pull --quiet-build --build -d

      - name: Install dependencies
        working-directory: pascoa_scout_server
        run: dart pub get

      - name: Install Serverpod CLI
        working-directory: pascoa_scout_server
        run: dart pub global activate serverpod_cli $VERSION

      - name: Run Serverpod generator
        working-directory: pascoa_scout_server
        run: serverpod generate

      - name: Run tests
        working-directory: pascoa_scout_server
        run: dart test

      - name: Stop containers
        if: always()
        working-directory: pascoa_scout_server
        run: docker compose down -v
